### ISSUE TITLE
Database error with "Code Bits"

### ISSUE THREAD

**Issue by adamkiss** [adamkiss/alfred-noteplan#27]
From the Discord message

```
[13:15:00.104] Logging Started...
[13:15:08.612] Noteplan[Script Filter] Queuing argument 't'
[13:15:08.724] Noteplan[Script Filter] Queuing argument 'te'
[13:15:08.810] Noteplan[Script Filter] Script with argv 't' finished
[13:15:08.814] ERROR: Noteplan[Script Filter] Code 255: Unhandled exception:
SqliteException(1): incomplete input, SQL logic error (code 1)
  Causing statement:             INSERT INTO main.code_bits (filename, note_type, language, title, content)
            VALUES 

#0      throwException (package:sqlite3/src/ffi/impl/exception.dart:38)
#1      DatabaseImpl._prepareInternal (package:sqlite3/src/ffi/impl/database.dart:247)
#2      DatabaseImpl.prepare (package:sqlite3/src/ffi/impl/database.dart:149)
#3      Dbs.insert_code_bits (package:alfred_noteplan/dbs.dart:125)
#4      refresh (package:alfred_noteplan/refresh.dart:23)
#5      main (file:///Users/adam/Code/alfred-noteplan/bin/noteplan.dart:72)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

**Comment by adamkiss** [comment]
🤦🏻

This was fixed in #dc42ad0, but unreleased yet.
